// tests/helpers/mock-provider.ts — Mock LLM provider for unit tests

import type { LLMProvider, GenerateOptions, ProviderError } from '../../src/providers/index.js';

const MOCK_SPEC_CONTENT = `# Mock Project — Spec

## Overview
This is a mock spec generated by the test provider.
It covers basic requirements for unit testing.

## Technical Design

### Architecture
Monolithic Node.js application with Express.

### API / Endpoints
- GET /api/items — list items
- POST /api/items — create item

### Data Model
\`\`\`
Item { id: number, name: string, createdAt: Date }
\`\`\`

## Testing Strategy
Unit tests with Vitest, integration tests with Supertest.

## Task List
| # | Task | Priority | Estimate |
|---|------|----------|----------|
| 1 | Setup project | High | 2h |
| 2 | Implement API | High | 4h |
| 3 | Write tests | Medium | 2h |
| 4 | Documentation | Low | 1h |
`;

export class MockProvider implements LLMProvider {
  readonly name = 'mock';
  readonly requiresApiKey = false;
  readonly timeoutMs = 5000;

  /** Override content for specific test scenarios */
  mockContent: string = MOCK_SPEC_CONTENT;

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async *generate(_prompt: string, _options: GenerateOptions): AsyncIterable<string> {
    // Yield content in chunks to simulate streaming
    const chunkSize = 100;
    for (let i = 0; i < this.mockContent.length; i += chunkSize) {
      yield this.mockContent.slice(i, i + chunkSize);
    }
  }

  parseError(error: unknown): ProviderError {
    return {
      type: 'unknown',
      message: String(error),
      retryable: false,
    };
  }
}

export const MOCK_SPEC_CONTENT_EXPORTED = MOCK_SPEC_CONTENT;
