/**
 * Interview Mode — 10 fixed sequential questions
 * Generates a structured SRS document from user answers.
 *
 * Used by: generate.ts when --interview flag is passed
 */

import { input } from '@inquirer/prompts';
import chalk from 'chalk';
import path from 'path';
import { writeFile } from '../utils/file.js';

// 10 fixed sequential questions from the proposal
const INTERVIEW_QUESTIONS = [
  { id: 'projectName', question: 'What is the project name?', type: 'input' as const },
  { id: 'description', question: 'Describe the project in 2-3 sentences.', type: 'input' as const },
  { id: 'domain', question: 'What domain/industry is this for? (e.g., e-commerce, healthcare, fintech)', type: 'input' as const },
  { id: 'targetUsers', question: 'Who are the target users? (list roles, comma-separated)', type: 'input' as const },
  { id: 'coreFeatures', question: 'What are the 3-5 core features? (comma-separated)', type: 'input' as const },
  { id: 'techStack', question: 'What tech stack? (e.g., "React + Node.js + PostgreSQL" or "recommend")', type: 'input' as const },
  { id: 'constraints', question: 'What are the key constraints? (budget, timeline, compliance, etc.)', type: 'input' as const },
  { id: 'deployment', question: 'How will this be deployed? (cloud provider, Docker, serverless, etc.)', type: 'input' as const },
  { id: 'integrations', question: 'Any existing systems to integrate with? (APIs, databases, services)', type: 'input' as const },
  { id: 'success', question: 'What does success look like in 6 months?', type: 'input' as const },
];

export interface InterviewAnswers {
  [key: string]: string;
}

/**
 * Run the 10-question interview and generate a structured SRS document.
 * Returns the path to the generated SRS file.
 */
export async function runInterview(outputDir: string): Promise<string> {
  console.log(chalk.bold('\n  autospec generate --interview\n'));
  console.log(chalk.dim('  Answer 10 questions to generate your requirements document.\n'));

  const answers: InterviewAnswers = {};

  for (let i = 0; i < INTERVIEW_QUESTIONS.length; i++) {
    const q = INTERVIEW_QUESTIONS[i];
    console.log(chalk.dim(`  [${i + 1}/10]`));
    answers[q.id] = await input({ message: q.question });
  }

  // Generate structured SRS markdown
  const srs = generateSrsFromAnswers(answers);

  // Write to specs/.interview-srs.md
  const srsPath = path.join(outputDir, '.interview-srs.md');
  await writeFile(srsPath, srs);

  console.log(chalk.green(`\n  ✓ Requirements saved to ${srsPath}\n`));
  console.log(chalk.dim('  Proceeding to spec generation...\n'));

  return srsPath;
}

function generateSrsFromAnswers(answers: InterviewAnswers): string {
  const users = answers.targetUsers.split(',').map(u => u.trim()).filter(Boolean);
  const features = answers.coreFeatures.split(',').map(f => f.trim()).filter(Boolean);
  const constraints = answers.constraints.split(',').map(c => c.trim()).filter(Boolean);

  return `# ${answers.projectName} — Software Requirements Specification

## 1. Project Overview

${answers.description}

**Domain:** ${answers.domain}

## 2. Target Users

${users.map(u => `- ${u}`).join('\n')}

## 3. Core Features

${features.map((f, i) => `### ${i + 1}. ${f}\n\n[To be detailed during spec generation]`).join('\n\n')}

## 4. Technical Stack

${answers.techStack === 'recommend' ? 'The AI should recommend an appropriate tech stack based on the project requirements.' : answers.techStack}

## 5. Constraints

${constraints.map(c => `- ${c}`).join('\n')}

## 6. Deployment

${answers.deployment}

## 7. Integrations

${answers.integrations || 'No existing integrations specified.'}

## 8. Success Criteria (6-month horizon)

${answers.success}

---

*Generated by AutoSpec interview mode on ${new Date().toISOString().split('T')[0]}*
`;
}
